export interface CountryInfo {
  nameJa: string;
  capitalJa: string;
}

// ニュース頻出国 約80か国
export const COUNTRY_DATA: Record<string, CountryInfo> = {
  // ── Asia（アジア）──
  JP: { nameJa: "日本", capitalJa: "東京" },
  CN: { nameJa: "中国", capitalJa: "北京" },
  KR: { nameJa: "韓国", capitalJa: "ソウル" },
  IN: { nameJa: "インド", capitalJa: "ニューデリー" },
  ID: { nameJa: "インドネシア", capitalJa: "ジャカルタ" },
  TH: { nameJa: "タイ", capitalJa: "バンコク" },
  VN: { nameJa: "ベトナム", capitalJa: "ハノイ" },
  PH: { nameJa: "フィリピン", capitalJa: "マニラ" },
  MM: { nameJa: "ミャンマー", capitalJa: "ネーピードー" },
  BD: { nameJa: "バングラデシュ", capitalJa: "ダッカ" },
  PK: { nameJa: "パキスタン", capitalJa: "イスラマバード" },
  AF: { nameJa: "アフガニスタン", capitalJa: "カブール" },
  IQ: { nameJa: "イラク", capitalJa: "バグダッド" },
  IR: { nameJa: "イラン", capitalJa: "テヘラン" },
  IL: { nameJa: "イスラエル", capitalJa: "エルサレム" },
  PS: { nameJa: "パレスチナ", capitalJa: "ラマッラー" },
  SY: { nameJa: "シリア", capitalJa: "ダマスカス" },
  SA: { nameJa: "サウジアラビア", capitalJa: "リヤド" },
  AE: { nameJa: "アラブ首長国連邦", capitalJa: "アブダビ" },
  TR: { nameJa: "トルコ", capitalJa: "アンカラ" },
  KZ: { nameJa: "カザフスタン", capitalJa: "アスタナ" },
  KH: { nameJa: "カンボジア", capitalJa: "プノンペン" },
  MY: { nameJa: "マレーシア", capitalJa: "クアラルンプール" },
  SG: { nameJa: "シンガポール", capitalJa: "シンガポール" },
  LK: { nameJa: "スリランカ", capitalJa: "スリジャヤワルダナプラコッテ" },
  NP: { nameJa: "ネパール", capitalJa: "カトマンズ" },
  TW: { nameJa: "台湾", capitalJa: "台北" },
  KP: { nameJa: "北朝鮮", capitalJa: "平壌" },
  MN: { nameJa: "モンゴル", capitalJa: "ウランバートル" },
  LA: { nameJa: "ラオス", capitalJa: "ビエンチャン" },
  BN: { nameJa: "ブルネイ", capitalJa: "バンダルスリブガワン" },
  TL: { nameJa: "東ティモール", capitalJa: "ディリ" },
  UZ: { nameJa: "ウズベキスタン", capitalJa: "タシケント" },
  TM: { nameJa: "トルクメニスタン", capitalJa: "アシガバート" },
  KG: { nameJa: "キルギス", capitalJa: "ビシュケク" },
  TJ: { nameJa: "タジキスタン", capitalJa: "ドゥシャンベ" },
  GE: { nameJa: "ジョージア", capitalJa: "トビリシ" },
  AM: { nameJa: "アルメニア", capitalJa: "エレバン" },
  AZ: { nameJa: "アゼルバイジャン", capitalJa: "バクー" },
  JO: { nameJa: "ヨルダン", capitalJa: "アンマン" },
  LB: { nameJa: "レバノン", capitalJa: "ベイルート" },
  KW: { nameJa: "クウェート", capitalJa: "クウェート" },
  QA: { nameJa: "カタール", capitalJa: "ドーハ" },
  BH: { nameJa: "バーレーン", capitalJa: "マナーマ" },
  OM: { nameJa: "オマーン", capitalJa: "マスカット" },
  YE: { nameJa: "イエメン", capitalJa: "サヌア" },
  BT: { nameJa: "ブータン", capitalJa: "ティンプー" },
  MV: { nameJa: "モルディブ", capitalJa: "マレ" },

  // ── Europe（ヨーロッパ）──
  GB: { nameJa: "イギリス", capitalJa: "ロンドン" },
  DE: { nameJa: "ドイツ", capitalJa: "ベルリン" },
  FR: { nameJa: "フランス", capitalJa: "パリ" },
  IT: { nameJa: "イタリア", capitalJa: "ローマ" },
  ES: { nameJa: "スペイン", capitalJa: "マドリード" },
  NL: { nameJa: "オランダ", capitalJa: "アムステルダム" },
  BE: { nameJa: "ベルギー", capitalJa: "ブリュッセル" },
  PL: { nameJa: "ポーランド", capitalJa: "ワルシャワ" },
  UA: { nameJa: "ウクライナ", capitalJa: "キーウ" },
  RU: { nameJa: "ロシア", capitalJa: "モスクワ" },
  SE: { nameJa: "スウェーデン", capitalJa: "ストックホルム" },
  NO: { nameJa: "ノルウェー", capitalJa: "オスロ" },
  FI: { nameJa: "フィンランド", capitalJa: "ヘルシンキ" },
  DK: { nameJa: "デンマーク", capitalJa: "コペンハーゲン" },
  CH: { nameJa: "スイス", capitalJa: "ベルン" },
  AT: { nameJa: "オーストリア", capitalJa: "ウィーン" },
  GR: { nameJa: "ギリシャ", capitalJa: "アテネ" },
  PT: { nameJa: "ポルトガル", capitalJa: "リスボン" },
  IE: { nameJa: "アイルランド", capitalJa: "ダブリン" },
  CZ: { nameJa: "チェコ", capitalJa: "プラハ" },
  RO: { nameJa: "ルーマニア", capitalJa: "ブカレスト" },
  HU: { nameJa: "ハンガリー", capitalJa: "ブダペスト" },
  SK: { nameJa: "スロバキア", capitalJa: "ブラチスラバ" },
  BG: { nameJa: "ブルガリア", capitalJa: "ソフィア" },
  HR: { nameJa: "クロアチア", capitalJa: "ザグレブ" },
  RS: { nameJa: "セルビア", capitalJa: "ベオグラード" },
  SI: { nameJa: "スロベニア", capitalJa: "リュブリャナ" },
  BA: { nameJa: "ボスニア・ヘルツェゴビナ", capitalJa: "サラエボ" },
  ME: { nameJa: "モンテネグロ", capitalJa: "ポドゴリツァ" },
  MK: { nameJa: "北マケドニア", capitalJa: "スコピエ" },
  AL: { nameJa: "アルバニア", capitalJa: "ティラナ" },
  LT: { nameJa: "リトアニア", capitalJa: "ビリニュス" },
  LV: { nameJa: "ラトビア", capitalJa: "リガ" },
  EE: { nameJa: "エストニア", capitalJa: "タリン" },
  IS: { nameJa: "アイスランド", capitalJa: "レイキャビク" },
  LU: { nameJa: "ルクセンブルク", capitalJa: "ルクセンブルク" },
  MT: { nameJa: "マルタ", capitalJa: "バレッタ" },
  CY: { nameJa: "キプロス", capitalJa: "ニコシア" },
  BY: { nameJa: "ベラルーシ", capitalJa: "ミンスク" },
  MD: { nameJa: "モルドバ", capitalJa: "キシナウ" },
  MC: { nameJa: "モナコ", capitalJa: "モナコ" },
  AD: { nameJa: "アンドラ", capitalJa: "アンドラ・ラ・ベリャ" },
  LI: { nameJa: "リヒテンシュタイン", capitalJa: "ファドゥーツ" },
  SM: { nameJa: "サンマリノ", capitalJa: "サンマリノ" },
  VA: { nameJa: "バチカン", capitalJa: "バチカン" },
  XK: { nameJa: "コソボ", capitalJa: "プリシュティナ" },

  // ── Americas（南北アメリカ）──
  US: { nameJa: "アメリカ", capitalJa: "ワシントンD.C." },
  CA: { nameJa: "カナダ", capitalJa: "オタワ" },
  MX: { nameJa: "メキシコ", capitalJa: "メキシコシティ" },
  BR: { nameJa: "ブラジル", capitalJa: "ブラジリア" },
  AR: { nameJa: "アルゼンチン", capitalJa: "ブエノスアイレス" },
  CO: { nameJa: "コロンビア", capitalJa: "ボゴタ" },
  CL: { nameJa: "チリ", capitalJa: "サンティアゴ" },
  VE: { nameJa: "ベネズエラ", capitalJa: "カラカス" },
  PE: { nameJa: "ペルー", capitalJa: "リマ" },
  CU: { nameJa: "キューバ", capitalJa: "ハバナ" },
  EC: { nameJa: "エクアドル", capitalJa: "キト" },
  BO: { nameJa: "ボリビア", capitalJa: "ラパス" },
  PY: { nameJa: "パラグアイ", capitalJa: "アスンシオン" },
  UY: { nameJa: "ウルグアイ", capitalJa: "モンテビデオ" },
  GY: { nameJa: "ガイアナ", capitalJa: "ジョージタウン" },
  SR: { nameJa: "スリナム", capitalJa: "パラマリボ" },
  PA: { nameJa: "パナマ", capitalJa: "パナマシティ" },
  CR: { nameJa: "コスタリカ", capitalJa: "サンホセ" },
  GT: { nameJa: "グアテマラ", capitalJa: "グアテマラシティ" },
  HN: { nameJa: "ホンジュラス", capitalJa: "テグシガルパ" },
  SV: { nameJa: "エルサルバドル", capitalJa: "サンサルバドル" },
  NI: { nameJa: "ニカラグア", capitalJa: "マナグア" },
  BZ: { nameJa: "ベリーズ", capitalJa: "ベルモパン" },
  DO: { nameJa: "ドミニカ共和国", capitalJa: "サントドミンゴ" },
  HT: { nameJa: "ハイチ", capitalJa: "ポルトープランス" },
  JM: { nameJa: "ジャマイカ", capitalJa: "キングストン" },

  // ── Africa（アフリカ）──
  ZA: { nameJa: "南アフリカ", capitalJa: "プレトリア" },
  NG: { nameJa: "ナイジェリア", capitalJa: "アブジャ" },
  EG: { nameJa: "エジプト", capitalJa: "カイロ" },
  ET: { nameJa: "エチオピア", capitalJa: "アディスアベバ" },
  KE: { nameJa: "ケニア", capitalJa: "ナイロビ" },
  SD: { nameJa: "スーダン", capitalJa: "ハルツーム" },
  CD: { nameJa: "コンゴ民主共和国", capitalJa: "キンシャサ" },
  GH: { nameJa: "ガーナ", capitalJa: "アクラ" },
  TZ: { nameJa: "タンザニア", capitalJa: "ドドマ" },
  MA: { nameJa: "モロッコ", capitalJa: "ラバト" },
  DZ: { nameJa: "アルジェリア", capitalJa: "アルジェ" },
  TN: { nameJa: "チュニジア", capitalJa: "チュニス" },
  LY: { nameJa: "リビア", capitalJa: "トリポリ" },
  CM: { nameJa: "カメルーン", capitalJa: "ヤウンデ" },
  CI: { nameJa: "コートジボワール", capitalJa: "ヤムスクロ" },
  SN: { nameJa: "セネガル", capitalJa: "ダカール" },
  ML: { nameJa: "マリ", capitalJa: "バマコ" },
  BF: { nameJa: "ブルキナファソ", capitalJa: "ワガドゥグー" },
  NE: { nameJa: "ニジェール", capitalJa: "ニアメ" },
  TD: { nameJa: "チャド", capitalJa: "ンジャメナ" },
  MG: { nameJa: "マダガスカル", capitalJa: "アンタナナリボ" },
  MZ: { nameJa: "モザンビーク", capitalJa: "マプト" },
  AO: { nameJa: "アンゴラ", capitalJa: "ルアンダ" },
  ZM: { nameJa: "ザンビア", capitalJa: "ルサカ" },
  ZW: { nameJa: "ジンバブエ", capitalJa: "ハラレ" },
  UG: { nameJa: "ウガンダ", capitalJa: "カンパラ" },
  RW: { nameJa: "ルワンダ", capitalJa: "キガリ" },
  SO: { nameJa: "ソマリア", capitalJa: "モガディシュ" },
  ER: { nameJa: "エリトリア", capitalJa: "アスマラ" },
  DJ: { nameJa: "ジブチ", capitalJa: "ジブチ" },
  MW: { nameJa: "マラウイ", capitalJa: "リロングウェ" },
  BW: { nameJa: "ボツワナ", capitalJa: "ハボローネ" },
  NA: { nameJa: "ナミビア", capitalJa: "ウィントフック" },
  SS: { nameJa: "南スーダン", capitalJa: "ジュバ" },
  GA: { nameJa: "ガボン", capitalJa: "リーブルビル" },
  CG: { nameJa: "コンゴ共和国", capitalJa: "ブラザビル" },
  GN: { nameJa: "ギニア", capitalJa: "コナクリ" },
  SL: { nameJa: "シエラレオネ", capitalJa: "フリータウン" },
  LR: { nameJa: "リベリア", capitalJa: "モンロビア" },
  MR: { nameJa: "モーリタニア", capitalJa: "ヌアクショット" },
  GM: { nameJa: "ガンビア", capitalJa: "バンジュール" },
  GQ: { nameJa: "赤道ギニア", capitalJa: "マラボ" },
  CF: { nameJa: "中央アフリカ", capitalJa: "バンギ" },
  BI: { nameJa: "ブルンジ", capitalJa: "ギテガ" },
  TG: { nameJa: "トーゴ", capitalJa: "ロメ" },
  BJ: { nameJa: "ベナン", capitalJa: "ポルトノボ" },
  LS: { nameJa: "レソト", capitalJa: "マセル" },
  SZ: { nameJa: "エスワティニ", capitalJa: "ムババーネ" },
  KM: { nameJa: "コモロ", capitalJa: "モロニ" },
  MU: { nameJa: "モーリシャス", capitalJa: "ポートルイス" },
  SC: { nameJa: "セーシェル", capitalJa: "ビクトリア" },
  CV: { nameJa: "カーボベルデ", capitalJa: "プライア" },
  ST: { nameJa: "サントメ・プリンシペ", capitalJa: "サントメ" },
  GW: { nameJa: "ギニアビサウ", capitalJa: "ビサウ" },

  // ── Oceania（オセアニア）──
  AU: { nameJa: "オーストラリア", capitalJa: "キャンベラ" },
  NZ: { nameJa: "ニュージーランド", capitalJa: "ウェリントン" },
  FJ: { nameJa: "フィジー", capitalJa: "スバ" },
  PG: { nameJa: "パプアニューギニア", capitalJa: "ポートモレスビー" },
  SB: { nameJa: "ソロモン諸島", capitalJa: "ホニアラ" },
  VU: { nameJa: "バヌアツ", capitalJa: "ポートビラ" },
  WS: { nameJa: "サモア", capitalJa: "アピア" },
  TO: { nameJa: "トンガ", capitalJa: "ヌクアロファ" },
  KI: { nameJa: "キリバス", capitalJa: "タラワ" },
  MH: { nameJa: "マーシャル諸島", capitalJa: "マジュロ" },
  FM: { nameJa: "ミクロネシア", capitalJa: "パリキール" },
  PW: { nameJa: "パラオ", capitalJa: "マルキョク" },
  NR: { nameJa: "ナウル", capitalJa: "ヤレン" },
  TV: { nameJa: "ツバル", capitalJa: "フナフティ" },

  // ── Caribbean（カリブ海）──
  TT: { nameJa: "トリニダード・トバゴ", capitalJa: "ポートオブスペイン" },
  BB: { nameJa: "バルバドス", capitalJa: "ブリッジタウン" },
  BS: { nameJa: "バハマ", capitalJa: "ナッソー" },
  AG: { nameJa: "アンティグア・バーブーダ", capitalJa: "セントジョンズ" },
  DM: { nameJa: "ドミニカ国", capitalJa: "ロゾー" },
  GD: { nameJa: "グレナダ", capitalJa: "セントジョージズ" },
  KN: { nameJa: "セントクリストファー・ネイビス", capitalJa: "バセテール" },
  LC: { nameJa: "セントルシア", capitalJa: "カストリーズ" },
  VC: {
    nameJa: "セントビンセント・グレナディーン",
    capitalJa: "キングスタウン",
  },

  // ── Others（その他）──
  GL: { nameJa: "グリーンランド", capitalJa: "ヌーク" },
};

// 国旗画像URLを生成（flagcdn.com CDN）
export function getCountryFlagUrl(countryCode: string): string {
  return `https://flagcdn.com/24x18/${countryCode.toLowerCase()}.png`;
}

// 安全に国情報を取得（未登録の場合はコードをそのまま表示）
export function getCountryInfo(countryCode: string): CountryInfo {
  return (
    COUNTRY_DATA[countryCode] ?? {
      nameJa: countryCode,
      capitalJa: "---",
    }
  );
}
